### ISSUE TITLE
Version compatibility in {cmake} package config

### ISSUE THREAD

**Issue by gmgunter** [pyre/pyre#105]
When pyre is installed via CMake, it exports [package config files](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#id1) that help downstream CMake projects find the installed pyre software. The package config files include a [package version file](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#package-version-file) that describes the version of the pyre package and its compatibility with other pyre versions. So when a downstream CMake project wants to import pyre via [`find_package()`](https://cmake.org/cmake/help/latest/command/find_package.html), it can request a particular version number with which the found pyre package must be compatible.

Currently, pyre's version compatibility rule is set to `SameMinorVersion`, indicating that two pyre versions are compatible only if they share the same major & minor version numbers.

https://github.com/pyre/pyre/blob/4e0d6bc117c2c4a6b4a51477f3120ba6f354a687/CMakeLists.txt#L172

So if, for example, a downstream CMake project requires pyre>=1.11 and uses

```cmake
find_package(pyre 1.11 REQUIRED CONFIG)
```

but the system had pyre=1.12 installed instead, their CMake build will fail since an incompatible pyre version was found.

This version compatibility rule may be inconvenient if pyre's minor version changes frequently, since only a narrow subset of pyre versions will be considered compatible with each other. Based on our offline discussions, it sounds like successive minor versions of pyre are generally compatible, so a looser rule might be more consistent with pyre's versioning strategy as well as more user-friendly.

Possible options to consider:

* Change the version compatibility rule to `SameMajorVersion` (see [the docs](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file) for details), indicating that successive minor releases are backwards compatible within the same major version family. I think this option is intended to be consistent with a [semantic versioning policy](https://semver.org/), so if pyre were to adopt this rule, we would want to be sure to increment the major version number of any release that introduces breaking changes to the API.

   However, it's not really clear to me from the CMake docs whether this compatibility rule also implies forwards compatibility. That is, if a downstream project requests pyre>=1.11 for example, would CMake consider pyre=1.10 to be a compatible version (since they have the same major version number)? Would need to test this to be sure.

* Alternatively, it looks like CMake 3.19 has added the capability for downstream projects to specify a version *range* when importing a package via `find_package()`. So maybe the best approach would be to keep the current `SameMinorVersion` compatibility rule, but suggest to downstream packages that they should request a version range when importing pyre, e.g.

   ```cmake
   find_package(pyre 1.11...2 CONFIG)  # request a pyre version >=1.11 but <2
   ```

I'm mainly opening this issue to try and spark a discussion since I'm not sure what the best strategy would be or even if any changes are really warranted.

cc @aivazis @rtburns-jpl

**Comment by aivazis** [comment]
i would think that having pyre=1.10.x be an answer to pyre>=1.11 would imply that the version matching algorithm is broken. i'm happy to change COMPATIBILITY to SameMajorVersion, if @rtburns-jpl has no objections

**Comment by aivazis** [comment]
sorry this took so long. i'm switching COMPATIBILITY to `SameMajorVersion` in the absence of objections.
