### ISSUE TITLE
`undefined symbol` error in `pyre.cpython-311-x86_64-linux-gnu.so` when loading `libc.so`

### ISSUE THREAD

**Issue by scottstanie** [pyre/pyre#108]
A strange error came up when testing a new environment (python 3.11, pyre 1.12.1):

```python
In [1]: import pyre
In [2]: import ctypes
In [3]: ctypes.CDLL('libc.so.6', mode=4)
```
```python-traceback
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[3], line 1
----> 1 ctypes.CDLL('libc.so.6', mode=4)

File /u/aurora-r0/staniewi/miniconda3/envs/mapping-311/lib/python3.11/ctypes/__init__.py:376, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    373 self._FuncPtr = _FuncPtr
    375 if handle is None:
--> 376     self._handle = _dlopen(self._name, mode)
    377 else:
    378     self._handle = handle

OSError: /u/aurora-r0/staniewi/miniconda3/envs/mapping-311/lib/python3.11/site-packages/pyre/extensions/pyre.cpython-311-x86_64-linux-gnu.so: undefined symbol: _ZN4pyre2py6memory5heapsERN8pybind117module_E
```

Even weirder is that running the same code again works the second time
```ipython
In [4]: ctypes.CDLL('libc.so.6', mode=4)
Out[4]: <CDLL 'libc.so.6', handle 7f29ff5104c8 at 0x7f29ef7b2510>
```

(Note: the real reason this came up was by using https://github.com/joblib/threadpoolctl to control the number of threads in isce3 within a python script)

```
In [5]: pyre.__version__
Out[5]: (1, 12, 1, '')

```

**Comment by aivazis** [comment]
ooops! this looks like a failure to adjust the `cmake` build after new bindings were introduced. i will get right on it and cut a new release asap.

do you mind helping me figure out what i have to do to trigger a conda-forge rebuild without adjusting the pyre version number?

**Comment by scottstanie** [comment]
Sure thing! I think it might be described here https://github.com/conda-forge/pyre-feedstock/#updating-pyre-feedstock which says that you just need to open a new PR to the feedstock repository once it's changed, and
> If the version of a package is not being increased, please add or increase the [build/number](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#build-number-and-string).

(which would change from 0 to 1 here https://github.com/conda-forge/pyre-feedstock/blob/main/recipe/meta.yaml#L16)

but i'll check if there's something else needed to re-trigger it

**Comment by aivazis** [comment]
ok. the fix is in. @rtburns-jpl, do you mind taking a quick look to verify that the make build works for you? and then, maybe trigger the condo-forge re-build? thx!

 @scottstanie, thanks for catching this...

**Comment by scottstanie** [comment]
>what do I need to do to reproduce the error?

I think the minimum example would be 
```python
In [1]: import pyre
In [2]: import ctypes
In [3]: ctypes.CDLL('libc.so.6', mode=4)
```

**Comment by aivazis** [comment]
Well, the `ctypes` path is a bit of a red herring. The actual fault is that `pyre.libpyre is None  == True` because the bindings from the faulty build had an unresolved symbol. Checking that

```
import pyre
assert pyre.libpyre
```

passes should be enough to verify the build is good. I should probably add this as a test to the test suite...

**Comment by aivazis** [comment]
Weird. `pyre/tests/pyre.ext/sanity.py` is exactly this test. So this should have been caught by CI

**Comment by aivazis** [comment]
mystery solved: the `cmake` build doesn't know about the `pyre.ext` test suite. so CI never had a chance  to catch this error. i'll fix this asap.

@rtburns, i think we are ready to pull the "build=1" trigger on conda-forge. would you like to do the honors?

**Comment by scottstanie** [comment]
Fixed by https://github.com/conda-forge/pyre-feedstock/pull/29
