### ISSUE TITLE
"Duplicate base class" TypeError on multiple inheritance of classes that implement Pyre protocols

### ISSUE THREAD

**Issue by Tyler-g-hudson** [pyre/pyre#113]
This error appears any time a class is subclass of any two or more classes that implement a Pyre protocol.

Examples:
Multiple inheritance with no shared base classes:
```python
# -*- coding: utf-8 -*-
import pyre

class Protocol(pyre.protocol, family=''):
    ...

class Base1(pyre.component, family='', implements=Protocol):
    ...

class Base2(pyre.component, family='', implements=Protocol):
    ...

class Class(Base1, Base2, family=''):
    ...
```

Multiple inheritance with a diamond structure:
```python
# -*- coding: utf-8 -*-
import pyre

class Protocol(pyre.protocol, family=''):
    ...

class Base(pyre.component, family='', implements=Protocol):
    ...

class Subclass1(Base, family=''):
    ...

class Subclass2(Base, family=''):
    ...

class SubSubclass(Subclass1, Subclass2, family=''):
    ...
```

These cases fail with `TypeError: duplicate base class Protocol`.
This error occurs whether or not subclasses implement any additional functionality beyond the base classes or protocol.

**Comment by aivazis** [comment]
@Tyler-g-hudson, do you mind checking whether this is still a problem after 87f6b1b7aafb028b99ee11938f9fe694fa4f539b?
