### ISSUE TITLE
Parallel STL algorithms

### ISSUE THREAD

**Issue by gmgunter** [pyre/pyre#116]
In cf01c9c, pyre started including the `<execution>` standard library header

https://github.com/pyre/pyre/blob/66bcd9e0d8a4b527bb2f1a555c3cce10d3d8d63b/lib/pyre/viz/external.h#L17

This library feature was added [in C++17](https://en.cppreference.com/w/cpp/header/execution) but implementers still only provide limited support for it:

* GCC libstdc++>=9 supports it, but requires linking against Intel TBB

  > The Parallel Algorithms have an external dependency on Intel TBB 2018 or later. If the <execution> header is included then -ltbb must be used to link to TBB.[^1]

* Clang libc++>=17 has partial support, but requires the [`-fexperimental-library`](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-fexperimental-library) flag[^2][^3]

This is kind of a headache. I think it might be preferable to wait for both GCC and Clang support for parallel STL features to mature a bit more before depending on it.

In my cursory inspection of the library, I couldn't find anywhere where we're actually using the contents of the `<execution>` header. A search for `std::execution` in the repo turned up no hits. I wonder if we could simply remove the `#include` statement?

[^1]: https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#table.cxx17_features
[^2]: https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features
[^3]: https://libcxx.llvm.org/Status/PSTL.html

**Comment by aivazis** [comment]
My memory fails me as to why this was needed in the first place. I have removed the `#include <execution>` from `pyre/viz/externals.h` in 88acb618cfbb44d8058aec86871fe7e2f03446af; let's see whether the test suite passes.

**Comment by gmgunter** [comment]
Looks like all tests are passing so I'll go ahead and close this. Thanks, @aivazis!
