### ISSUE TITLE
Do not use "PROJ_LIB" in config and Make.mm

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#14]
PROJ_LIB is a standard environment variable used for PROJ.4/5 libraries. When users try to use virtual environments with package managers, this variable is set correctly for different software to work. "config" hijacks this variable and this leads to build issues for pyre and isce3.

**Comment by aivazis** [comment]
Pitush,

I’m not sure what proj4 is. config has been using this variable since 1992. i doubt the proj4 developers were old enough to program at the time 😀

Do you have a recommendation as to how to proceed? Should we upgrade to mm 4.0 where everything is in a private namespace? Any other ideas?

-- Michael

**Comment by EJFielding** [comment]
Hi Michael,

Happy New Year!

Actually, the “Proj” software was first written in the early 1980’s with version 4 released in 1994, according to Wikipedia (https://en.wikipedia.org/wiki/PROJ.4). I don’t know when they started using the PROJ_LIB environment variable.

How soon do we have to migrate to “mm 4.0” anyway?

++Eric

**Comment by aivazis** [comment]
A gathering of dinosaurs...

We can migrate anytime. mm 4.0 was meant to be he last transitional step to merlin, the full python solution. I’ve been using it since last May and it’s fairly stable. It can build pyre and altar already, making it build isce 3 should be relatively straight forward.

-- Michael

**Comment by piyushrpt** [comment]
I noticed few places where PROJ_LIB is being used. Renaming these to something else like PROJECT_LIB or something similar might resolve the issue. PROJ_LIB also shows up in a couple of places in pyre's Make.mm files.

**Comment by aivazis** [comment]
In config, PROJ_XXX is a family of a couple of dozen variables that capture project specific configuration options. Changing only PROJ_LIB would create inconsistencies. 

Before going any further, I would like to understand why there is any crosstalk between building pyre with config and a random third party library. Can you provide a description of the failure so we can diagnose?

-- Michael

**Comment by piyushrpt** [comment]
PROJ_LIB is an environment variable that is used by numerous mapping based software - PROJ.4, pyproj, matplotlib.basemap, mapserver. Often when running tests with mm or when building with mm, this variable that points to a folder gets in the way as mm expects it to be a library leading to an error message as shown below:

```
g++ -DCXX_ID="gcc-4.x" -DDEBUG -DBLD_PROCEDURE -DWITH_TIME -I/home/galtamas/tools/pyre/config/platform/Linux-3.x -I/home/galtamas/tools/pyre/config/compiler/gcc-4.x -I/home/galtamas/tools/pyre/config/compiler/gcc-4.x -I/home/galtamas/tools/pyre/config/target/Linux-3.x_x86_64 -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include -I/home/galtamas/tools/pyre/install/include  -Wall  -g        -std=c++17  bcd.cc -o bcd    -g        -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib -L/home/galtamas/tools/pyre/install/lib    -lrt
./bcd
ar d /home/galtamas/python/anaconda3/envs/customGcc6/share/proj
ar: /home/galtamas/python/anaconda3/envs/customGcc6/share/proj: Is a directory
```

**Comment by aivazis** [comment]
Then a solution might be to set the environment variable only when needed, or explicitly unset it for the invocation of mm, e.g. unset PROJ_LIB || mm

-- Michael
