### ISSUE TITLE
Docker pyre build - list of hacks

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#15]
Here are the current set of hacks that need to be implemented to get docker to build pyre with conda

```
&& git clone $PYRE_CONFIG_REPO \
 # disable some tests that fail during docker build
 && sed -i 's|${PYTHON} ./tcp.py|#${PYTHON} ./tcp.py|g' tests/pyre/ipc/Make.mm \
 && sed -i 's|externals|#externals|g' tests/pyre/Make.mm \
 && sed -i 's|RECURSE_DIRS += postgres|#RECURSE_DIRS += postgres|g' tests/Make.mm \
 && sed -i 's|postgres|#postgres|g' examples/bizbook.pyre/tests/Make.mm \
 && sudo mv /opt/conda/share/proj /opt/conda/share/proj.orig \
&& sudo python3 ~/tmp/pyre/config/make/mm.py --prefix=/opt/pyre
```

1. TCP tests seem to fail consistently. This might be  due to the network configuration for the docker build. But failure cause the build to halt. Should probably be skipped. 

2. Externals test consistently fails when trying to access blas even though GSL support has been disabled
```
configure: configure:
  host: '*********'
  package manager: 'bare'
pyre.calc: component 'configure.blas', an instance of 'pyre.externals.blas.gslcblas' has no attribute 'bare'
configure: file='/home/galtamas/tools/pyre/install/packages/pyre/calc/Postprocessor.py', line=58, function='getValue': firewall breached; aborting...
```

3. These  tests can also be skipped by just not asking for postgres support. But when you do, they fail. 

4. This is same as #14 . Making this change breaks other software that uses PROJ.4, notably pyproj.

**Comment by aivazis** [comment]
You can also skip all the tests by asking mm to build only. “mm build” should do it. unless there is value in running the test suite every time.

-- Michael

**Comment by piyushrpt** [comment]
Closing.
