### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by EJFielding** [pyre/pyre#17]
What version of Python is required now for the full pyre test suite? I am using Python 3.6 and had an error message about a formatting parameter when I ran "mm" to include the tests. I was able to get pyre to build without the tests by running "mm build".

**Comment by aivazis** [comment]
Eric,

Could you please capture the error log and send it to me? I don’t use python 3.6 myself any more, so it’s hard for me to duplicate this behavior.

Thanks.

— Michael

**Comment by piyushrpt** [comment]
The arguments for python.locale module functions changed slightly between 3.6 and 3.7, and some of the locale tests fail.

**Comment by aivazis** [comment]
Currently, pyre will work with both 3.6 and 3.7. Python 3.7 introduced some backwards incompatible changes to the locale module. As a result, 3.7 is required for the test suite complete successfully.
