### ISSUE TITLE
Install portinfo in the include folder

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#2]
The "portinfo" file is not installed in the include folder, making the header files unusable. The install process should also install the "portinfo" file to allow pyre to be used as a stand-alone package.

**Comment by piyushrpt** [comment]
Is there an ETA for this feature? At present, it is not possible for users to build even simple single file examples that include pyre headers and link to pyre libraries due to the missing header. They often create an empty portinfo file and use it, which may be completely inconsistent with the way that pyre installation that they are using was built originally.

**Comment by aivazis** [comment]
Piyush,

I still don’t know how to implement it consistently without config. I also don’t know where to put such a file. We may have to write a configure script to generate it as part of the build when not using mm.

— Michael

**Comment by piyushrpt** [comment]
Would it be possible to install the config-generated "portinfo" into the installed include folder. This can be done when building pyre. This is the process used by armadillo, gdal etc. The auto-generated file is installed and made available under the include tree. 

At present, a new user cannot even write a simple single file c++ test - with a single compilation line -  that just includes pyre include folder and links against libpyre to ensure that he has installed things correctly at his end.

**Comment by aivazis** [comment]
Piyush,

portinfo itself includes a bunch of files scattered throughout the various config directories, based on run-time detection of platform, compiler, target, build type, and any other degrees of freedom the user has chosen. We can reduce this to a simpler standard set, but i would need to know specific build targets. Further, the alternative build system, whatever it may be, will have to communicate to the configure script where the install include directories are so we know where to deliver the autogenerated portinfo.

I’m surprised to hear that users’ simple c++ tests require portinfo. Adding the #include portinfo happens only in .cc files; no pyre header should depend on it. Perhaps you can show me an actual use case to debug?

— Michael

**Comment by piyushrpt** [comment]
Looks like updates to pyre over time have resolved the issue. I was still trying this simple example which would only work if you have an #include<portinfo> line at the top 

```cpp
#include <pyre/journal.h>

int main(int argc, char* argv[])
{
    pyre::journal::info_t info("testcase");

    info << "This is a simple pyre journal test case "
         << pyre::journal::endl;

    return 0;
}
```

**Comment by piyushrpt** [comment]
It would still make sense to install the portinfo file. There are numerous examples of CMake Module files using check_symbol_exists in C++ header files to determine the environment used to build/install a package. As long as the list of variables that are set by "config" are made available, an external build system can write a recipe to adapt to it.

**Comment by piyushrpt** [comment]
Following up on today's conversation. There are plenty of examples online for detecting architecture using cmake, e.g: https://github.com/civetweb/civetweb/blob/master/cmake/DetermineTargetArchitecture.cmake

There are whole set of related variable names that are auto-determined CMAKE_SYSTEM_NAME, CMAKE_HOST_SYSTEM_NAME etc that can be leveraged to write the rules. The compiler itself can be made to report its type with -dumpmachine flag.

Happy to provide more information and help put the cmake setup for portinfo
