### ISSUE TITLE
Modifying defaults for properties in derived class

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#20]
Here is an example: 

```.py
class BaseProduct(pyre.component, family='mission.productreader'):
     validId = pyre.properties.str(default='BASE')  
     validid.doc = ...
```

```.py
class DerivedProduct(BaseProduct):
     ....
 ```

I want to modify the default for validId to say `DERIVED`. Should `validId` be redefined as a property of the DerivedProduct or should this be modified with another mechanism? I did not find an example for this in the unit tests.

**Comment by aivazis** [comment]
Piyush,

Yes, the derived class must redeclare any traits it has inherited that it wants to modify in any way.

-- Michael

**Comment by piyushrpt** [comment]
Thanks. Just wanted to confirm.
