### ISSUE TITLE
Using clang for building pyre

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#21]
I see compilers/clang in config repository. How can I use this to build pyre? Is there a one line change. I tried overriding COMPILER_CXX_NAME in .mm/config.def but that doesn't seem to work.

**Comment by lijun99** [comment]
I used sudo port select --set gcc none to disable macports/gcc, which sets the default clang gcc/g++ in /usr/bin/.
Alternatively, use CC=clang CXX=clang++ mm.
-Lijun

On Tue, May 28, 2019 at 9:19 PM piyushrpt <notifications@github.com<mailto:notifications@github.com>> wrote:

I see compilers/clang in config repository. How can I use this to build pyre? Is there a one line change. I tried overriding COMPILER_CXX_NAME in .mm/config.def but that doesn't seem to work.

**Comment by piyushrpt** [comment]
Thanks @lijun99. That worked nicely.
