### ISSUE TITLE
Dependencies list for pyre 

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#23]
I'm trying to build pyre using conda. Build works fine but the recipes fail during staging and testing as its looking for "lscpu" on Linux box. Would be good to have all the assumed dependencies - so that this can be captured in the conda recipe. 

```
  File "/home/conda/feedstock_root/build_artifacts/pyre_1560999261911/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lscpu': 'lscpu'
Tests failed for pyre-1.0.1-py36hc9558a2_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for pyre-1.0.1-py36hc9558a2_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by piyushrpt** [comment]
The preliminary recipe for pyre can be found here: 

https://github.com/isce-framework/staged-recipes/tree/pyre

in the recipes/pyre folder. 

To test if the recipe works locally - you can run ./.circleci/run_docker_build.sh

**Comment by piyushrpt** [comment]
Unfortunately, lscpu is only way of getting the processor information and not supported by conda as it is not portable across platforms. Other packages seem to be using this approach:
https://github.com/workhorsy/py-cpuinfo/blob/master/cpuinfo/cpuinfo.py

This is also available on conda via py-Cpuinfo package

**Comment by piyushrpt** [comment]
We have linux binaries building with pull request conda-forge/staged-recipes#8604 

mm does not work with clang (3.8?). See CI results here: 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=43829

Flag -std=c++17 is invalid

**Comment by rtburns-jpl** [comment]
If the 4.0 feature set is sufficient mm could detect clang<5 and switch to -std=c++1z.

**Comment by piyushrpt** [comment]
Yeah. We don't get to control the compilers that get used. They provide a whole bunch of packages built with same set. 

Either that or we eliminate possibility of isce3 conda package for osx this early. I prefer extending mm to support the features. 

The unit test suite also doesnt work on both 3.6 / 3.7. If we want to exercise the test suite, we need to support both.
