### ISSUE TITLE
Question about pyre/primitives/Path.py/stem

### ISSUE THREAD

**Issue by lijun99** [pyre/pyre#25]
Michael,

Suppose I have a path "path1/path2/static.data.txt".  I would call ".txt" as suffix or extension, and "static.data" as stem. The current definition of stem, to use name.find('.') (the first dot) rather than name.rfind('.') (the last dot) will return 'static'. 

If I change the stem definition with name.rfind, altar-1.1 breaks down. The reason might be, the cython extensions have names like ext.cpython-37m-x86_64-linux-gnu.so, and stem will not get "ext" as desired. 

I wonder what is your convention for stem, nameWithoutSuffix, or nameWithoutSuffixes. Or shall we provide different names for these two cases?

**Comment by aivazis** [comment]
I'm not sure what the right answer is.

The comments around the implementation of stem indicate that it is the portion of the name up to the last '.', but the actual implementation scans to the first.

The module pathlib also agrees with you.

So perhaps we can fix this. I worry about breaking existing code silently, but that's also something that we can try to manage.

In terms of names for the various cases, I would prefer to fix stem and document it correctly, and add another method that splits on '.' and lets users pick out what they need

**Comment by lijun99** [comment]
I would prefer to keep stem as it is: at least I know altar-1.1 breaks if we change its definition.

Maybe similar to suffix and suffixes, we define stem and stems, for filename up to the first '.', and to the last '.', respectively.

**Comment by aivazis** [comment]
`path.stem` now obeys the `pathlib` convention and returns the file name without the trailing suffix. fixed in 337beac93e313f8ea3db4740ce0e9b02f11b2c58
