### ISSUE TITLE
Provide means to query install configuration

### ISSUE THREAD

**Issue by piyushrpt** [pyre/pyre#3]
Provide means to query the flavor of pyre installed similar to

<pre>
numpy.get_include()
numpy.__config.__show()
</pre>

**Comment by aivazis** [comment]
Is the `pyre-config` app sufficient, or do you need access to this information from within a python session?

**Comment by piyushrpt** [comment]
@aivazis - I think it might be useful to expose the config via a python function - that returns a string / dict. Some examples:

```
import numpy  #Also similar for scipy 
numpy.__config__.get_info(componentName)


import cv2
cv2.getBuildInformation()
```

Just the executable is sufficient for build systems to detect the install locations.

**Comment by aivazis** [comment]
ok. i'll add this asap
