### ISSUE TITLE
Fix auto-versioning for release tarballs

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#33]
Since the auto-versioning logic in cmake queries git for version info, it fails when installing from source that isn't git-cloned, e.g. when using the release tarball.
```
-- Found Git: /usr/bin/git (found version "2.7.4") 
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at .cmake/pyre_init.cmake:101 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:37 (pyre_getVersion)


CMake Error at CMakeLists.txt:40 (project):
  VERSION ".." format invalid.
```

**Comment by aivazis** [comment]
protecting the build against `git describe` failing is relatively straight-forward. any ideas about where the version information should come from in this case? should i add a version file somewhere when packing the tarball?

**Comment by rtburns-jpl** [comment]
I can't speak as to what would work best here, but I think a version file would work fine for me.

**Comment by rtburns-jpl** [comment]
I found a fix for this, now that I understand the intention of the functions in pyre/.cmake. I now see that since our module path is before pyre's, I can add my own pyre_init.cmake which will override pyre's. I then include pyre's pyre_init.cmake, but override pyre_getVersion with a hard-coded version instead of git describe.

I think this fix would still be a nice convenience but it's not necessary for me anymore.
