### ISSUE TITLE
New mm with Anaconda3 on mac

### ISSUE THREAD

**Issue by lijun99** [pyre/pyre#44]
I tried to use the new mm to compile pyre with Anaconda3 on mac and had the Segmentation Fault 11 problem when importing cpython modules. The cause, as I found, is that Anaconda3's libpython3.7m.dylib needs to be linked as '-undefined dynamic_lookup' rather than '-lpython3.7m'. Cmake 3.16 seems to address the issue correctly in FindPython. I wonder whether similar arrangements can be made to the new mm.

**Comment by aivazis** [comment]
is the flag "-undefined dynamic_lookup" understood by all compilers on macOS? is it a replacement for "-lpython3.7m" or an addition? can you poke around a bit more so we can figure out where to park this? 

it's bit strange that everything seems to work correctly outside anaconda. is it possible that this would imply codifying an anaconda deficiency into the build system? perhaps supporting anaconda would require some type of isolation from the rest of the build environments we support.

an alternative might be for you to use cmake to build with anaconda and not  touch mm at all. is that acceptable?

**Comment by rtburns-jpl** [comment]
Pybind11 does this whenever linking on macOS, and has a good description of the issue in the comments:
https://github.com/pybind/pybind11/blob/4f72ef846fe8453596230ac285eeaa0ce3278bb4/tools/pybind11Tools.cmake#L179

**Comment by lijun99** [comment]
Ryan, thanks for the link!
Michael, cmake with Anaconda works: if I check the verbose info, it actually uses "-undefined dynamic_lookup" without "-lpython3.7m" or libpython3.7m.dylib. This flag has been included in cmake Modules/FindPython. I want to figure out an easy way to install pyre+altar on Mac, 1) if new mm works by changing some link flags, that's definitely my favorite; otherwise, 2) we can stick to macports python3, or 3) write a cmake for altar.  What do you think?

**Comment by aivazis** [comment]
Lijun,

i think the simplest path forward is to write cmake files for altar. are you familiar enough with cmake to take this on?

**Comment by lijun99** [comment]
I can try.

**Comment by aivazis** [comment]
don't worry. i took care of it. if you know how to build with cmake, could you please give it a try?
