### ISSUE TITLE
Fix failing unit tests

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#51]
The most recent Travis log https://travis-ci.org/github/pyre/pyre/builds/665015848 shows the following unit tests failing:
- [x] journal.debug-activation (Failed)
- [x] journal.error-activation (Failed)
- [x] journal.firewall-activation (Failed)
- [x] journal.warning-activation (Failed)
- [x] pyre.components.component_aliases (Failed)
- [x] pyre.config.configurator_locators (Failed)
- [ ] pyre.filesystem.zip (Failed)
- [x] pyre.framework.executive_shelves (Failed)
- [ ] pyre.primitives.path_resolution (Failed)
- [x] pyre.schemata.istreams (Failed)
- [ ] python.locale_codec (Failed)
- [ ] libpyre.grid.grid-direct-get (Failed)
- [x] libpyre.journal.debug-envvar (Child aborted)
- [x] libpyre.journal.debug (Child aborted)
- [x] libpyre.journal.firewall (Child aborted)

Also, these tests are commented out in the cmake files as they do not currently build:
- [ ] libpyre.memory.direct-clone
- [ ] libpyre.memory.constdirect-clone

**Comment by rtburns-jpl** [comment]
Not sure how best to collaborate on this. If you give me push perms on a separate branch I have some initial fixes I can push.

**Comment by aivazis** [comment]
Happy to give you full perms. I just don't see a way to give you direct access. Do I have to make you an owner of the organization?

**Comment by rtburns-jpl** [comment]
I really dont know, I was hoping there was an option for just a single branch so we could work on one for this issue. Maybe per-repo settings are as granular as it gets

**Comment by aivazis** [comment]
I don't even see a way to give full access to the pyre repo. i'll just make you an owner of the organization

**Comment by rtburns-jpl** [comment]
Ok, thanks! I'll try not to break anything ;)

**Comment by aivazis** [comment]
well, you are a member of the @pyre/core team. i just granted that team write access to the repo. can you give it a try? you should have full write access now

**Comment by aivazis** [comment]
if that fails, we'll take it up a notch

**Comment by rtburns-jpl** [comment]
Whoops that PR wasn't totally finished.

**Comment by aivazis** [comment]
looks like the tests are running with python 3.6. is this easy to fix?

**Comment by rtburns-jpl** [comment]
Yeah just change this https://github.com/pyre/pyre/blob/10beb3ebf255019239c1b5db207766acea91e265/.travis.yml#L15

I think there's a way to have it run on several python versions

**Comment by aivazis** [comment]
I'm trying to run test on my machine so I don't have to keep making commits to invoke travis. I'm having a couple of problems. For starters, I have an mip installation, which cmake finds. It builds the pyre MPI wrappers and the extension module correctly, but fails when compiling the MPI test cases because the compile/link line is missing the MPI include path and libraries. How do I fix this?

**Comment by rtburns-jpl** [comment]
If MPI is found there will be an MPI::MPI_CXX target that propagates the right include path + libs. I'll push a commit to the fix-tests branch

**Comment by aivazis** [comment]
can you make this apply only to the MPI tests?

**Comment by rtburns-jpl** [comment]
Ah it looks like the MPI tests will have to be set up manually since they require custom args. I'll take a closer look

**Comment by aivazis** [comment]
i'm a bit confused about how pyre_python_test is supposed to work. In pyre/tests/CMakeLists.txt, line 701, you run every tests in $testfiles through the function, followed another paragraph of tests cases with extra arguments. Is this intended to run the test cases with AND without the extra arguments, or are test cases with extra arguments executed only with their command line?

**Comment by rtburns-jpl** [comment]
Yeah I tried to match the functionality from the corresponding Make.mm file. I removed the files from testfiles which aren't run without arguments, but it looked like a few of the files were meant to be run with and without args. Now "testfiles" might be more accurately named "noarg_testfiles" but I left the old name to keep the diff as small as possible.

W.r.t. mpi, I think the most principled approach here would be to create a pyre::pyre_mpi target which propagates the pyre core lib along with pyre's mpi extensions. That target would be used internally for the mpimodule as well as the test cases, as well as exported to end users. I might need to circle back to this one in a couple days.

**Comment by aivazis** [comment]
sounds good, and thanks for taking the time to do this.

i've done some clean up of the obvious cases. a few more are failing because the mm driven tests suite does some prepping ahead of time, e.g. build zip files to be opened, creates a directory structure to be navigated, etc. i'll come back to those later

**Comment by aivazis** [comment]
ok. i pushed my fixes to {fix-tests}. off to other things for now. thanks again

**Comment by rtburns-jpl** [comment]
Any idea why the travis checks aren't showing up on recent commits? The most recent red X for me is from march 20.

**Comment by aivazis** [comment]
same here. no idea. is it possible travis integration broke somehow?

**Comment by rtburns-jpl** [comment]
Not sure, maybe a permission thing? I can pull up the travis page for the org and they've all been running, it's just the checks that don't appear for some reason.

**Comment by rtburns-jpl** [comment]
Oh cool, looks like you fixed it

**Comment by aivazis** [comment]
random walk through their recommendations. ended up moving to travis-ci.com. nothing else would work for pyre. the other repos migrated painlessly. still not sure what the problem was

**Comment by aivazis** [comment]
i commented out the remaining ones. they either require complicated prep or the travis runtime lacks support for them (the locale_codec test seems to fail because there is no support for the locales)
