### ISSUE TITLE
Compiler support for <filesystem>

### ISSUE THREAD

**Issue by gmgunter** [pyre/pyre#57]
Recently (since v1.9.9), journal has added a [dependency on the STL `<filesystem>` header](https://github.com/pyre/pyre/blob/f1e8e76663e9608cd608e69aeea3cbabb53d6f3e/lib/journal/externals.h#L24). Older versions of gcc and clang do not have library support for `std::filesystem` and even some more recent versions require special flags to build & link projects with this dependency. I think it's worth considering how best to handle this in order to support as many compilers as possible and avoid build system complications for users.

- gcc >= 8.0 supports `#include <filesystem>` (gcc < 9.1 requires linking with `-lstdc++fs`)
- clang >= 7.0 supports `#include <filesystem>` (clang < 9.0 requires linking with `-lc++fs` or `-lstdc++fs`)

Here are a few suggestions:

1. Fall back to `#include <experimental/filesystem>` if `<filesystem>` is not available. This would improve support for older compiler versions. I'm not aware of what differences exist between the two implementations but I believe they're largely interchangeable.
1. Update the CMake system to automatically identify when a special library must be linked and add the necessary flags. This should simplify the build process for most users.

For (1), I believe we could use the c++17 feature [`__has_include()`](https://en.cppreference.com/w/cpp/preprocessor/include) for this, e.g.:

```cpp
#if __has_include(<filesystem>)
#    include <filesystem>
#else 
#    include <experimental/filesystem>
#endif

#if __has_include(<filesystem>)
namespace fs = std::filesystem;
#else 
namespace fs = std::experimental::filesystem;
#endif
```

For (2), it seems there is no builtin CMake feature for automatically detecting whether `-lc++fs` or `-lstdc++fs` is needed, although people have implemented some hand-rolled approaches. @rtburns-jpl pointed out a [possible solution](https://gitlab.kitware.com/cmake/cmake/-/issues/17834#note_649902) that involves trying to compile a simple dummy program using `<filesystem>` with various flags to determine which is needed.

Any thoughts on these suggestions? Should I make a PR?

**Comment by rtburns-jpl** [comment]
Note that the gcc / clang version requirements outlined above are actually libstdc++ / libc++ requirements. Since these can be mixed and matched, a robust solution needs to inspect the compiler configuration to determine which standard library is being used independently of the compiler. Also note that any solution (including the one in my pull request) that depends on running test executables, such as via `check_cxx_source_runs`, will preclude cross compilation. Also note that Apple has explicitly excluded std::fs from pre-10.15 AppleClang.

Considering all of these pain points, I would strongly urge you to consider any of
- removing std::fs usage entirely
- sequestering it into a separate and strictly optional component
- wrapping its use in a forward declared pimpl class so the dependency is not propagated via public headers

**Comment by aivazis** [comment]
well, it appears in the `journal` public API so that users can specify the path to a log file. but since no path arithmetic is being done at the moment, we could just switch to expecting an `std::string`. i'd prefer to look for alternatives before going down any regressive paths, if that's at all possible

**Comment by aivazis** [comment]
@gmgunter : do you mind checking that the `cmake` changes by @rtburns-jpl that were just merge solve your problem? they haven't caused any problems with my setup, so that's half the battle...

**Comment by gmgunter** [comment]
Yup, this seems to work well for me (thanks, @rtburns-jpl). Everything builds fine on gcc v10.2 and cmake correctly fails with a helpful diagnostic on gcc v7.5. 

A good test would be to try it w/ 8.0 <= gcc < 9.1 (which should compile but requires linking to a particular library). spack doesn't seem to want to install any of the intervening versions of gcc for me, so I'll have to put that test off for now.

Note that there will still be some friction with isce3's compiler support. isce3 aims to support some compilers older than gcc v8.0 & clang v7.0, which don't have library support for `std::filesystem`. It's great that cmake now fails gracefully for those compilers, but I suspect we'll need a solution that still allows pyre to build in that case or else isce3 will have difficulty bumping pyre versions.

**Comment by aivazis** [comment]
For the record, this is not a compiler issue; it's a library issue. The `libc++` library distributed by the LLVM project has a host of deficiencies relative to C++17 currently; poor support for `std::filesystem` is not the only one. Conversely, even relatively old versions of `clang++` are able to compile using the current version of `libstdc++`, the library from the `gcc` project.

This issue has a very quick fix: drop `std::filesystem::path` in favor of `std::string`. However, I'd like to explore whether there is a more civil solution to this problem. Does `cmake` have a way of detecting/controlling which c++ runtime it is going to link with?

**Comment by gmgunter** [comment]
> Does cmake have a way of detecting/controlling which c++ runtime it is going to link with?

There's not a builtin way to check this that I'm aware of. I think what you might do is compile a simple program within cmake to check whether the [preprocessor macros](https://stackoverflow.com/a/31658120/6038094) defined by each STL implementation are defined.

My sense is that we're still a ways away from having widespread stable library support for `std::filesystem`. I think the safest solution would be to stick with the lowest common denominator, which is `std::string`, for now and only adopt `std::filesystem::path` when it doesn't require build system tricks to do so.
