### ISSUE TITLE
<sys/sysctl.h> doesn't exist on Alpine Linux

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#63]
Alpine installs linux-specific development headers to /usr/include/linux as part of the linux-headers package. Maybe it would be better to include simply <sysctl.h> and detect the linux-specific header include dir? Looks like this is the only change needed for installing on alpine linux.

https://pkgs.alpinelinux.org/contents?file=sysctl.h&path=&name=linux-headers&branch=edge&repo=main&arch=x86

**Comment by aivazis** [comment]
It's on the to-do list; see #54. i'm looking for something sane to replace gathering cpuinfo . lscpu is not installed by default on some distributions, /proc is polluted by x86-isms so its unusable on ppc64le, and <sys/sysctl.h> has been deprecated for 25 years and finally about to be removed.

ideas welcome...
