### ISSUE TITLE
locale_codec test failure due to unicode currency symbol

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#65]
It looks like the locale_codec test expects the euro symbol to be "Eu" in the output string, but sometimes it will instead be the "€'" symbol.

Dockerfile (contains snippet from locale_codec.py test):
```Dockerfile
FROM condaforge/linux-anvil
RUN /opt/conda/bin/python -c '\
import locale; \
locale.setlocale(locale.LC_ALL, "el_GR.UTF-8"); \
expected = "1.234.567,89 Eu"; \
got = locale.currency(1234567.89, True, True, False); \
print(got); \
assert got == expected \
'
```

Relevant output:
```
 ---> Running in 103842d28bcd
1.234.567,89€
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
```

**Comment by aivazis** [comment]
This test case is temporarily disabled as of f231334cca5bc6360f33f65fb3c8b7f746ebaabb. There is much too much instability in the canonical currency representations across python versions for this test to be useful
