### ISSUE TITLE
Use of ABCs from 'collections' instead of 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by gmgunter** [pyre/pyre#67]
I stumbled across this deprecation warning in a recent test log:

```
//home/gunter/Tools/isce3/packages/pyre/descriptors/Typed.py:98
  //home/gunter/Tools/isce3/packages/pyre/descriptors/Typed.py:98: DeprecationWarning: Using or importing the ABCs from
 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    if isinstance(processors, collections.Iterable):
```

It's triggered from [here](https://github.com/pyre/pyre/blob/c02a7726e9a9860f52952e2143ac62ef7f14610d/packages/pyre/descriptors/Typed.py#L98), though there may be other instances that I missed. Looks like we should patch this before python 3.9 is released.

**Comment by aivazis** [comment]
Hunted them all down and fixed them. Thanks for catching this; it wasn't even on my radar...
