### ISSUE TITLE
Replace Travis CI pipeline

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#68]
Travis CI isn't free for open source anymore :(
Let's find a suitable replacement - maybe CircleCI or Azure

**Comment by aivazis** [comment]
predictable. it has been an obvious hook for a while. any idea what others do?

**Comment by rtburns-jpl** [comment]
I'm pretty impressed with Azure's offerings, they claim to give out unlimited minutes for open source and support Windows + macOS + Linux.
https://github.com/marketplace/azure-pipelines
We use CircleCI for isce2 and it works well. It has limited minutes but I think the runners are a bit faster.
https://github.com/marketplace/circleci
There are many more of course, that I know less about. No rush to pick one, as I assume our current stash of Travisbucks will last a while.

**Comment by aivazis** [comment]
are you opposed to learning GitHub actions?

**Comment by rtburns-jpl** [comment]
Not at all, probably a very useful thing to learn actually! I've seen some powerful things done with it, and they're looking to roll out Actions for Github Enterprise soon

**Comment by rtburns-jpl** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by rtburns-jpl** [comment]
Your new pipelines look great! I think this can be closed now.
