### ISSUE TITLE
Heap.icc: no matching constructor

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#70]
I am seeing a compilation error while building `tests/pyre.lib/memory/heap_access.cc` for the pyre 1.10.0 release. I'm using Clang 7 (non-Apple) on macOS. It looks like this test was backported from p2.

```
In file included from /tmp/nix-build-python3.8-pyre-1.10.0.drv-0/source/tests/pyre.lib/memory/heap_access.cc:8:
In file included from /tmp/nix-build-python3.8-pyre-1.10.0.drv-0/source/build/lib/pyre/memory.h:28:
In file included from /tmp/nix-build-python3.8-pyre-1.10.0.drv-0/source/build/lib/pyre/memory/public.h:22:
In file included from /tmp/nix-build-python3.8-pyre-1.10.0.drv-0/source/build/lib/pyre/memory/Heap.h:82:
/tmp/nix-build-python3.8-pyre-1.10.0.drv-0/source/build/lib/pyre/memory/Heap.icc:18:5: error: no matching constructor for initialization of 'pyre::memory::Heap<double, false>::handle_type' (aka 'shared_ptr<pyre::memory::Heap<double, false>::value_type []>')
    _data{ new value_type[cells] },
    ^    ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by aivazis** [comment]
This is a deficiency in the C++17 compliance of `libc++`: `std::shared_ptr` is missing the array constructor. 

However, this does remind me to take another look and decide whether there is a real reason to use this constructor over the pointer one. If i remember correctly, the difference is which deallocator will get called: `delete` vs `delete []`. The details are hazy by now, so I'll take another look.

**Comment by rtburns-jpl** [comment]
Ah yeah I was wondering if this was a clang 7 issue. A workaround would be great but I can bump my toolchain if needed.

**Comment by rtburns-jpl** [comment]
FYI not sure what clang version fixed this, but this works under clang/libcxx 11. Would be nice to have a workaround since everything else seems to work on clang 7, but not high priority.

**Comment by aivazis** [comment]
do you mind checking one more time that all is ok, now that clang7 is a fossil?
