### ISSUE TITLE
macOS clock/time functionality requires 10.12 SDK

### ISSUE THREAD

**Issue by rtburns-jpl** [pyre/pyre#77]
I am trying to bump our conda-forge package, but they are apparently building against the 10.9 SDK (which uses this incomplete time.h header: https://opensource.apple.com/source/Libc/Libc-997.90.3/include/time.h.auto.html) so many clock/time definitions aren't available.

```cpp
lib/pyre/timers/ProcessClock.icc:20:19: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &t);
                  ^
1 error generated.
```

According to https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks, "While the default version 10.9 can be overridden using the following changes to the recipe, it should be done as a last resort. Please consult with core team if this is something you think you need."

So it may be simpler for us to conditionally stub out that call.

**Comment by aivazis** [comment]
@rtburns, i think this should be ok now. d2c6b136d19ac5698fc6fcdf869eb735005e2e1c put your recommended guard around the timer instantiation. could you please verify and close the issue when you are happy?
