### ISSUE TITLE
render a fixed floe

### ISSUE THREAD

**Issue by AlecAivazis** [pyre/pyre#8]

**Comment by AlecAivazis** [comment]
@aivazis  - what do we want the `id` of the canonical floe to be? Should the client just ask for something like

```
{
    node(id: "canonical") {
        ... on Floe {

        }
    }
}
```

You could just ignore the `id` arg for now, and I can just ask for anything

**Comment by aivazis** [comment]
The floe sandbox has moved to https://github.com/aivazis/flocor
