### ISSUE TITLE
[GSL] Wrong suffix check when loading Vector/Matrix from binary file

### ISSUE THREAD

**Issue by tobiscode** [pyre/pyre#83]
Hi,

I've been trying to load a binary data file as the covariance for an AlTar DataL2 object but it seems that it tries to read the binary file as a text file since the suffix check is wrong.

In [Matrix.load](https://github.com/pyre/pyre/blob/b54e1492020b3a56385ceb5f7c17911f0802800f/packages/gsl/Matrix.py#L189) as well as [Vector.load](https://github.com/pyre/pyre/blob/b54e1492020b3a56385ceb5f7c17911f0802800f/packages/gsl/Vector.py#L203), the suffix check is for `suffix == "bin"` where it should be `suffix == ".bin"` - like it is in the `save` functions.

Changing this fixes the problem.

**Comment by aivazis** [comment]
Sorry about that. I just pushed a fix in aa69df38f70d5879511bdfdbb146b13b63082b96. Could you please verify that it fixes your problem?

**Comment by tobiscode** [comment]
Hi,
I'm sorry but I can't test it since I'm running the CUDA-fork of pyre from [lijun99/pyre](https://github.com/lijun99/pyre). If it gets selectively merged there, I could test it.
Cheers

**Comment by aivazis** [comment]
I don't think i have commit privileges to @lijun99 repositories. Feel free to get in touch with him and push a fix.

**Comment by aivazis** [comment]
Fixed in aa69df38f70d5879511bdfdbb146b13b63082b96
