### ISSUE TITLE
 Problem in installation of Pyre

### ISSUE THREAD

**Issue by aropragya** [pyre/pyre#88]
Hi there
We are installing pyre from github but facing an issue. While installing pyre from source (downloaded from: https://github.com/pyre/pyre ) and doing ./configure, it starts searching for pyre-1.0-boot.zip. we tried downloading this zip file from: http://pyre.orthologue.com/pyre-1.0-boot.zip but the page is giving error 404 (Not Found).
Meanwhile we also downloaded pyre-boot.zip from https://github.com/pyre/pyre/releases, however we are not able to understand how to install pyre-boot. 
Kindly reply at the earliest and let us know how to install the package pyre. 
P.S: we are working in offline mode, so kindly guide us accordingly.
@aivazis @AlecAivazis @bryanvriel @lijun99 @ysant77

**Comment by lijun99** [comment]
You may use cmake or the [mm](https://github.com/aivazis/mm) build tool to compile/install pyre.
